package com.squad.chemistry.models

import kotlinx.serialization.SerialName


data class Element(
    val abundance_humans: String,
    val abundance_in_earth_crust_c1: String,
    val abundance_in_earth_crust_c2: String,
    val abundance_in_earth_crust_c3: String,
    val abundance_in_earth_crust_c4: String,
    val abundance_in_earth_crust_c5: String,
    val abundance_in_earth_crust_c6: String,
    val abundance_in_earth_crust_u1: String,
    val abundance_in_earth_crust_u2: String,
    val abundance_in_humans_2: String,
    val abundance_meteorite: String,
    val abundance_seawater_w1: String,
    val abundance_seawater_w2: String,
    val abundance_solar_system_y1: String,
    val abundance_solar_system_y2: String,
    val abundance_sun_s1: String,
    val abundance_urban_soil: String,
    val adiabatic_index: String,
    val allotrope_names: String,
    val alternate_name: String,
    val appearance: String,
    val atomic_mass: String,
    val atomic_mass_uncertainty: String,
    val atomic_radius_calculated: String,
    val atomic_radius_covalent_single_bond: String,
    val atomic_radius_covalent_triple_bond: String,
    val atomic_radius_empirical: String,
    val atomic_radius_metallic: String,
    val atomic_radius_rahm: String,
    val atomic_radius_vanderwaals: String,
    val atomic_volume: String,
    val autoignition_point: String,
    val block: String,
    val boil_CRC: String,
    val boil_LNG: String,
    val boil_WEL: String,
    val boil_Zhang: String,
    val boil_use: String,
    val brinell_hardness: String,
    val bulk_modulus: String,
    val c6_coeff: String,
    val c6_gb: String,
    val cas_number: String,
    val category: String,
    val cid_number: String,
    val covalent_radius_bragg: String,
    val covalent_radius_cordero: String,
    val covalent_radius_pyykko: Int,
    val covalent_radius_pyykko_double: String,
    val covalent_radius_pyykko_triple: String,
    val cpk_color: String,
    val critical_pressure: String,
    val critical_temperature: String,
    val curie_point: String,
    val decay_mode: String,
    val density_gas: String,
    val density_liquid_cr2: String,
    val density_rt: String,
    val density_solid_CRC: String,
    val density_solid_LNG: String,
    val density_solid_WEL: String,
    val description: String,
    val dipole_polarizability: String,
    val dipole_polarizability_unc: String,
    val discovery_location: String,
    val dot_number: String,
    val ea_content_id: Int,
    val electrical_resistivity_273K: String,
    val electrical_resistivity_293K: String,
    val electrical_resistivity_298K: String,
    val electrical_resistivity_300K: String,
    val electrical_resistivity_500K: String,
    val electrical_resistivity_80K: String,
    val electrical_type: String,
    val electron_affinity_eV: String,
    val electron_affinity_kJmol: String,
    val electron_configuration: String,
    val electron_configuration_semantic: String,
    val electronegativity_allen: String,
    val electronegativity_ghosh: String,
    val electronegativity_pauling: String,
    val enthalpy_of_fusion: String,
    val etymological_description: String,
    val eu_number: String,
    val evaporation_heat: String,
    val flashpoint: String,
    val gas_phase: String,
    val geochemical_class: String,
    val glawe_number: Int,
    val goldschmidt_class: String,
    val group: String,
    val half_life: String,
    val heat_of_combustion: String,
    val heat_of_fusion_crc: String,
    val heat_of_fusion_lng: String,
    val heat_of_fusion_wel: String,
    val heat_of_vaporization_crc: String,
    val heat_of_vaporization_lng: String,
    val heat_of_vaporization_wel: String,
    val heat_of_vaporization_zhang: String,
    @SerialName("ionization_energies-0")
    val ionization_energies_zero: String,
    @SerialName("ionization_energies-1")
    val ionization_energies_one: String,
    @SerialName("ionization_energies-2")
    val ionization_energies_two: String,
    @SerialName("ionization_energies-3")
    val ionization_energies_three: String,
    @SerialName("ionization_energies-4")
    val ionization_energies_four: String,
    @SerialName("ionization_energies-5")
    val ionization_energies_five: String,
    @SerialName("ionization_energies-6")
    val ionization_energies_six: String,
    @SerialName("ionization_energies-7")
    val ionization_energies_seven: String,
    @SerialName("ionization_energies-8")
    val ionization_energies_eight: String,
    @SerialName("ionization_energies-9")
    val ionization_energies_nine: String,
    @SerialName("ionization_energies-10")
    val ionization_energies_ten: String,
    @SerialName("ionization_energies-11")
    val ionization_energies_eleven: String,
    @SerialName("ionization_energies-12")
    val ionization_energies_twelve: String,
    @SerialName("ionization_energies-13")
    val ionization_energies_thirteen: String,
    @SerialName("ionization_energies-14")
    val ionization_energies_fourteen: String,
    @SerialName("ionization_energies-15")
    val ionization_energies_fifteen: String,
    @SerialName("ionization_energies-16")
    val ionization_energies_sixteen: String,
    @SerialName("ionization_energies-17")
    val ionization_energies_seventeen: String,
    @SerialName("ionization_energies-18")
    val ionization_energies_eighteen: String,
    @SerialName("ionization_energies-19")
    val ionization_energies_nineteen: String,
    @SerialName("ionization_energies-20")
    val ionization_energies_twenty: String,
    @SerialName("ionization_energies-21")
    val ionization_energies_twenty_one: String,
    @SerialName("ionization_energies-22")
    val ionization_energies_twenty_two: String,
    @SerialName("ionization_energies-23")
    val ionization_energies_twenty_three: String,
    @SerialName("ionization_energies-24")
    val ionization_energies_twenty_four: String,
    @SerialName("ionization_energies-25")
    val ionization_energies_twenty_five: String,
    @SerialName("ionization_energies-26")
    val ionization_energies_twenty_six: String,
    @SerialName("ionization_energies-27")
    val ionization_energies_twenty_seven: String,
    @SerialName("ionization_energies-28")
    val ionization_energies_twenty_eight: String,
    @SerialName("ionization_energies-29")
    val ionization_energies_twenty_nine: String,
    val is_radioactive: Int,
    val isolated_sampled_by: String,
    val isolation_sample_year: String,
    val jmol_color: String,
    val language_of_origin: String,
    val lattice_angles: String,
    val lattice_constant: String,
    val lattice_constant_internal_default_radii: String,
    val lattice_structure: String,
    val lifetime: String,
    val magnetic_ordering: String,
    val magnetic_susceptibility: String,
    val meaning: String,
    val melt_CRC: String,
    val melt_LNG: String,
    val melt_WEL: String,
    val melt_use: String,
    val mendeleev_number: Int,
    val metallic_radius_c12: String,
    val metallic_radius_mendeleev: String,
    val mohs_hardness: String,
    val molar_heat: String,
    val molar_volume: String,
    val molcas_gv_color: String,
    val name_en: String,
    val name_tr: String,
    val named_by: String,
    val neel_point: String,
    val neutron_cross_section: String,
    val neutron_mass_absorption: String,
    val number: Int,
    val observation_or_discovery_year: String,
    val observed_predicted_by: String,
    val origin_of_word: String,
    val original_word: String,
    val oxidation_states: String,
    val period: Int,
    val pettifor_number: Int,
    val phase_at_stp: String,
    val poisson_ratio: String,
    val proton_affinity: String,
    val quantum_number: String,
    val refractive_index: String,
    val rtecs_number: String,
    val shear_modulus: String,
    @SerialName("shells-0")
    val shells_zero: Int,
    @SerialName("shells-1")
    val shells_one: Int,
    @SerialName("shells-2")
    val shells_two: Int,
    @SerialName("shells-3")
    val shells_three: Int,
    @SerialName("shells-4")
    val shells_four: Int,
    @SerialName("shells-5")
    val shells_five: Int,
    @SerialName("shells-6")
    val shells_six: Int,
    @SerialName("shells-7")
    val shells_seven: Int,
    val sources: String,
    val space_group_number: String,
    val specific_heat_capacity: String,
    val specific_heat_crc: String,
    val specific_heat_lng: String,
    val specific_heat_wel: String,
    val spectral_img: String,
    val speed_of_sound_extensional: String,
    val speed_of_sound_fluid: String,
    val speed_of_sound_longitudinal: String,
    val speed_of_sound_transversal: String,
    val superconducting_point: String,
    val symbol: String,
    val symbol_origin: String,
    val thermal_conductivity: String,
    val thermal_expansion: String,
    val uses: String,
    val vdw_radius_alvarez: String,
    val vdw_radius_batsanov: String,
    val vdw_radius_bondi: String,
    val vdw_radius_dreiding: String,
    val vdw_radius_mm3: String,
    val vdw_radius_rt: String,
    val vdw_radius_truhlar: String,
    val vdw_radius_uff: String,
    val vickers_hardness: String,
    val wikipedia: String,
    val xpos: Int,
    val youngs_modulus: String,
    val ypos: Int,
)